import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar with explicit structure for complete navigation
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Analysis',
      link: {
        type: 'generated-index',
        title: 'Project Analysis',
        description: 'Comprehensive analysis of three open-source car rental projects: BookCars, Car Rental PHP, and FreeCar.',
        slug: '/analysis',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'analysis',
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      link: {
        type: 'generated-index',
        title: 'Market Research',
        description: 'Industry standards, market trends, competitive analysis, and best practices in the car rental industry.',
        slug: '/research',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'research',
        },
      ],
    },
    {
      type: 'category',
      label: 'Stakeholders',
      link: {
        type: 'generated-index',
        title: 'Stakeholder Analysis',
        description: 'Identification and analysis of all stakeholders in the car rental ecosystem.',
        slug: '/stakeholders',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stakeholders',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflows',
      link: {
        type: 'generated-index',
        title: 'User Workflows',
        description: 'Comprehensive documentation of user scenarios and system workflows with visual diagrams.',
        slug: '/workflows',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'workflows',
        },
      ],
    },
    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
        title: 'Feature Catalog',
        description: 'Comprehensive catalog of features organized by categories, synthesized from analysis and research.',
        slug: '/features',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
    {
      type: 'category',
      label: 'Requirements',
      link: {
        type: 'generated-index',
        title: 'Requirements Specification',
        description: 'Formal requirements document following EARS patterns, covering functional, non-functional, integration, and compliance requirements.',
        slug: '/requirements',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'requirements',
        },
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      link: {
        type: 'generated-index',
        title: 'Appendices',
        description: 'Supporting documentation including glossary, references, traceability matrix, and methodology details.',
        slug: '/appendices',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'appendices',
        },
      ],
    },
  ],
};

export default sidebars;
